on: [push]

name: test_random_event

jobs:
  check:
    name: random_event
    runs-on: ubuntu-latest
    steps:
      - name: Install latest stable
        uses: actions/checkout@v2
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Run cargo test
        run: cargo test
        
